var m: Map<string, string> = new Map<string, string>();
m.set("nhl-C", "Centre")
m.set("nhl-LW", "Left winger")
m.set("nhl-RW", "Right winger")
m.set("nhl-D", "Defenseman")
m.set("nhl-G", "Goalie")
m.set("nba-G", "Guard")
m.set("nba-PG", "Point guard")
m.set("nba-SG", "Shooting guard")
m.set("nba-F", "Forward")
m.set("nba-SF", "Small forward")
m.set("nba-PF", "Power forward")
m.set("nba-C", "Center")
m.set("nfl-C", "Center")
m.set("nfl-QB", "Quarterback")
m.set("nfl-WR", "Wide receiver")
m.set("nfl-RB", "Running back")
m.set("nfl-TE", "Tight end")
m.set("nfl-C", "Center")
m.set("nfl-G", "Offensive guard")
m.set("nfl-T", "Tackle")
m.set("nfl-NT", "Nose tackle")
m.set("nfl-OT", "Offensive tackle")
m.set("nfl-DT", "Defensive tackle")
m.set("nfl-DE", "Defensive end")
m.set("nfl-DB", "Linebacker")
m.set("nfl-LB", "Linebacker")
m.set("nfl-ILB", "Inside linebacker")
m.set("nfl-OLB", "Outside linebacker")
m.set("nfl-MLB", "Middle linebacker")
m.set("nfl-CB", "Cornerback")
m.set("nfl-FS", "Free safety")
m.set("nfl-SS", "Strong safety")
m.set("nfl-S", "Safety")
m.set("nfl-K", "Kicker")
m.set("nfl-H", "Holder")
m.set("nfl-LS", "Long snapper")
m.set("nfl-P", "Punter")
m.set("nfl-KOS", "Kickoff specialist")
m.set("nfl-KR", "Kick returner")
m.set("nfl-PR", "Punt returner")
m.set("nfl-FB", "Fullback")
m.set("nfl-DE", "Defensive end")
m.set("mlb-1B","First base")
m.set("mlb-2B","Second base")
m.set("mlb-3B","Third base")
m.set("mlb-SS","Shortstop")
m.set("mlb-C", "Catcher")
m.set("mlb-CI","Corner infield")
m.set("mlb-MI","Middle infield")
m.set("mlb-IF","Infield")
m.set("mlb-LF","Left field")
m.set("mlb-CF","Center field")
m.set("mlb-RF","Right field")
m.set("mlb-OF","Outfield")
m.set("mlb-SP","Starting pitcher")
m.set("mlb-RP","Relief pitcher")
m.set("mlb-P", "Pitcher")
m.set("mlb-DH", "Designed hitter")

module.exports = {
  positionsMap: m
}